steps:
  - id: backend-setenv
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - echo $$BACKEND_ENV | base64 --decode > .env
    secretEnv: ["BACKEND_ENV"]

  - id: backend-build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/tooooools-api-ew1-$_ENV:$COMMIT_SHA
      - .

  - id: backend-push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/tooooools-api-ew1-$_ENV:$COMMIT_SHA

  - id: backend-deploy
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy tooooools-api-ew1-$_ENV \
        --project $PROJECT_ID \
        --image gcr.io/$PROJECT_ID/tooooools-api-ew1-$_ENV:$COMMIT_SHA \
        --allow-unauthenticated \
        --region europe-west1 \
        --port '8080' \
        --memory $_GCR_MEMORY \
        --timeout 3600

timeout: 3600s

images:
  - gcr.io/$PROJECT_ID/tooooools-api-ew1-$_ENV:$COMMIT_SHA

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/tooooools-api-env/versions/latest
      env: "BACKEND_ENV"
